version: "3"
services:
  db:
    image: mariadb:11.3.2
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./database/sample_dump.sql:/docker-entrypoint-initdb.d/dump.sql
  python:
    build: .
    entrypoint: >
      sh -c "sleep 3 && python3 main.py"
    env_file:
      - .env
    links:
      - db
